"""empty message

Revision ID: 016aef5c2ba8
Revises: 2693c24f5455
Create Date: 2023-07-09 17:01:08.646796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '016aef5c2ba8'
down_revision = '2693c24f5455'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contract', schema=None) as batch_op:
        batch_op.add_column(sa.Column('posted_by', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['posted_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contract', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('posted_by')

    # ### end Alembic commands ###
