"""empty message

Revision ID: 2764c50ef878
Revises: ba3203f82de0
Create Date: 2023-06-29 08:46:47.117034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2764c50ef878'
down_revision = 'ba3203f82de0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cmr_profile_home')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cmr_profile_home',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('home_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cmr_profile_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['cmr_profile_id'], ['cmr_profile.id'], name='cmr_profile_home_cmr_profile_id_fkey'),
    sa.ForeignKeyConstraint(['home_id'], ['home.id'], name='cmr_profile_home_home_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='cmr_profile_home_pkey')
    )
    # ### end Alembic commands ###
