"""empty message

Revision ID: 2c59c5866ef3
Revises: 1c088b739516
Create Date: 2023-07-06 11:36:21.252223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c59c5866ef3'
down_revision = '1c088b739516'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pro_profile', schema=None) as batch_op:
        batch_op.drop_column('verified')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pro_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verified', sa.BOOLEAN(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
