"""empty message

Revision ID: 33adbf0762c8
Revises: 459989c0a7d7
Create Date: 2023-06-17 10:26:22.726191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33adbf0762c8'
down_revision = '459989c0a7d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('role')
    # ### end Alembic commands ###
