"""empty message

Revision ID: 459989c0a7d7
Revises: 412bd22b9533
Create Date: 2023-06-17 09:15:25.585674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '459989c0a7d7'
down_revision = '412bd22b9533'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=120), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('username')

    # ### end Alembic commands ###
