"""empty message

Revision ID: 626659ce4e5a
Revises: f56af902fcd0
Create Date: 2023-06-27 06:44:34.811789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '626659ce4e5a'
down_revision = 'f56af902fcd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pro_profile', schema=None) as batch_op:
        batch_op.alter_column('address',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.alter_column('city',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.alter_column('phone_number',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pro_profile', schema=None) as batch_op:
        batch_op.alter_column('phone_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('city',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.alter_column('address',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)

    # ### end Alembic commands ###
