"""empty message

Revision ID: 7ac57d33a5d4
Revises: 18c5574f7887
Create Date: 2023-07-06 17:59:07.941689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ac57d33a5d4'
down_revision = '18c5574f7887'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pro_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('decode_city', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pro_profile', schema=None) as batch_op:
        batch_op.drop_column('decode_city')

    # ### end Alembic commands ###
