"""empty message

Revision ID: ba0f8abbe20f
Revises: 626659ce4e5a
Create Date: 2023-06-27 08:57:54.548057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba0f8abbe20f'
down_revision = '626659ce4e5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contract', schema=None) as batch_op:
        batch_op.add_column(sa.Column('finishing_time', sa.DateTime(), nullable=False))

    with op.batch_alter_table('home', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)

    with op.batch_alter_table('home__post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('starting_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('finishing_time', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('home__post', schema=None) as batch_op:
        batch_op.drop_column('finishing_time')
        batch_op.drop_column('starting_time')

    with op.batch_alter_table('home', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)

    with op.batch_alter_table('contract', schema=None) as batch_op:
        batch_op.drop_column('finishing_time')

    # ### end Alembic commands ###
