"""empty message

Revision ID: c386730b9596
Revises: d54635fb2b3c
Create Date: 2023-07-09 15:07:24.025837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c386730b9596'
down_revision = 'd54635fb2b3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contract', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_price', sa.Numeric(), nullable=True))

    with op.batch_alter_table('home', schema=None) as batch_op:
        batch_op.alter_column('postal_code',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('home', schema=None) as batch_op:
        batch_op.alter_column('postal_code',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)

    with op.batch_alter_table('contract', schema=None) as batch_op:
        batch_op.drop_column('total_price')

    # ### end Alembic commands ###
