"""empty message

Revision ID: f3fbb579096d
Revises: b85d45f60341
Create Date: 2023-07-05 18:07:12.271128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3fbb579096d'
down_revision = 'b85d45f60341'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('home', schema=None) as batch_op:
        batch_op.add_column(sa.Column('decode_city', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('home', schema=None) as batch_op:
        batch_op.drop_column('decode_city')

    # ### end Alembic commands ###
